name: mirinaestudy
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  get: ^4.6.6

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_native_splash: ^2.4.0
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0
  dropdown_button2: ^2.3.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  fonts:
    - family: NotoSansKRBold
      fonts:
        - asset: assets/fonts/NotoSansKR/NotoSansKR-Bold.ttf
    - family: NotoSansKRExtraBold
      fonts:
        - asset: assets/fonts/NotoSansKR/NotoSansKR-ExtraBold.ttf
    - family: NotoSansKRExtraLight
      fonts:
        - asset: assets/fonts/NotoSansKR/NotoSansKR-ExtraLight.ttf
    - family: NotoSansKRLight
      fonts:
        - asset: assets/fonts/NotoSansKR/NotoSansKR-Light.ttf
    - family: NotoSansKRMedium
      fonts:
        - asset: assets/fonts/NotoSansKR/NotoSansKR-Medium.ttf
    - family: NotoSansKRRegular
      fonts:
        - asset: assets/fonts/NotoSansKR/NotoSansKR-Regular.ttf
    - family: NotoSansKRSemiBold
      fonts:
        - asset: assets/fonts/NotoSansKR/NotoSansKR-SemiBold.ttf
    - family: NotoSansKRThin
      fonts:
        - asset: assets/fonts/NotoSansKR/NotoSansKR-Thin.ttf
    - family: NunitoSansBold
      fonts:
        - asset: assets/fonts/NunitoSans/NunitoSans_10pt-Bold.ttf
    - family: NunitoSansExtraBold
      fonts:
        - asset: assets/fonts/NunitoSans/NunitoSans_10pt-ExtraBold.ttf
    - family: NunitoSansExtraLight
      fonts:
        - asset: assets/fonts/NunitoSans/NunitoSans_10pt-ExtraLight.ttf
    - family: NunitoSansLight
      fonts:
        - asset: assets/fonts/NunitoSans/NunitoSans_10pt-Light.ttf
    - family: NunitoSansMedium
      fonts:
        - asset: assets/fonts/NunitoSans/NunitoSans_10pt-Medium.ttf
    - family: NunitoSansRegular
      fonts:
        - asset: assets/fonts/NunitoSans/NunitoSans_10pt-Regular.ttf
    - family: NunitoSansSemiBold
      fonts:
        - asset: assets/fonts/NunitoSans/NunitoSans_10pt-SemiBold.ttf

  uses-material-design: true

  assets:
    - assets/images/icons/
    - assets/images/
